language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
  - "rm -rf integration-tests"
script:
  - "meteor test-packages ./ --release 1.2.1"
